# Generated by Django 6.0.7 on 2026-07-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailEnvoye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinataire", models.EmailField(max_length=254)),
                ("type_email", models.CharField(max_length=50)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("objet", models.CharField(max_length=200)),
                ("statut_envoi", models.CharField(default="envoye", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("grade", models.CharField(blank=True, max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("vacataire", "Vacataire"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                ("departement", models.CharField(blank=True, max_length=100)),
                ("quota_heures_max", models.FloatField(default=192.0)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("coefficient", models.FloatField(default=1.0)),
                (
                    "type_enseignement",
                    models.CharField(
                        choices=[
                            ("CM", "Cours Magistral"),
                            ("TD", "Travaux Dirigés"),
                            ("TP", "Travaux Pratiques"),
                        ],
                        max_length=2,
                    ),
                ),
                ("volume_horaire_theorique", models.FloatField()),
                ("semestre", models.CharField(max_length=20)),
                ("departement", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueAffectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.CharField(max_length=20)),
                ("a_ete_affecte", models.BooleanField(default=True)),
                ("heures_realisees", models.FloatField(default=0.0)),
                ("heures_theoriques", models.FloatField(default=0.0)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.enseignant",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.CharField(max_length=20)),
                ("est_valide", models.BooleanField(default=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_etudes",
                        to="core.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeanceEmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_seance", models.DateField()),
                ("heure_debut", models.CharField(max_length=5)),
                ("heure_fin", models.CharField(max_length=5)),
                ("salle", models.CharField(blank=True, max_length=50)),
                ("semestre", models.CharField(max_length=20)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.enseignant",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evenement", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent_justifie", "Absent justifié"),
                            ("absent_injustifie", "Absent injustifié"),
                            ("maladie", "Maladie"),
                            ("retard", "Retard"),
                        ],
                        max_length=30,
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="core.enseignant",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.seanceemploidutemps",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voeu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.CharField(max_length=20)),
                ("score_preference", models.FloatField(default=0.5)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voeux",
                        to="core.enseignant",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AffectationTheorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semestre", models.CharField(max_length=20)),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.enseignant",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="core.module",
                    ),
                ),
            ],
            options={
                "unique_together": {("enseignant", "module", "semestre")},
            },
        ),
    ]
